apiVersion: v1
kind: Service
metadata: 
  name: pingpong-svc
  namespace: dev
  labels: 
    role: pingpong
spec:
  selector:
    role: pingpong
  ports:
    - port: 3000
      targetPort: 3000
  type: NodePort
