apiVersion: apps/v1
kind: Deployment 
metadata:
  name: pingpong-app
  namespace: dev
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 1
  revisionHistoryLimit: 4
  replicas: 1
  minReadySeconds: 20
  selector:
    matchLabels:
      role: pingpong
    matchExpressions:
      - {key: version, operator: In, values: [v1, v2, v3, v4, v5]}
  template: 
    metadata:
      name: pingpong
      labels: 
        app: nodejs
        role: pingpong
        version: v1 
    spec:
      containers: 
        - name: pingpong
          image: bennyamber/pingpong:v1 
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits: 
              memory: "128Mi"
              cpu: "250m"
          livenessProbe:
            tcpSocket:
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 3

